#! /bin/sh

sxhkd &
betterlockscreen --lock
setxkbmap -layout 'us,cz,ru(phonetic)'
feh --no-fehbg --bg-fill .config/bg2.jpg

picom --daemon -c
#pulseaudio --start

kill "$(pidof polybar)"
polybar barrr --quiet --reload &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor DP1 -d I II III IV V VI VII VIII IX X
bspc monitor DP2 -d I II III IV V VI VII VIII IX X

#bspc config border_width                2
#bspc config window_gap                  18
bspc config border_width                0
bspc config window_gap                  0
bspc config single_monocle              true
bspc config remove_disabled_monitors    true

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a 'Gpick' state=floating
bspc rule -a 'Pavucontrol' state=floating
bspc rule -a 'feh' state=floating
bspc rule -a 'Matplotlib' state=floating
bspc rule -a 'GNU Octave' state=floating
